name: Compare Files

on: [push]

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compare Files
        run: |
          diff andrea.log sreedevi.log > comparison.txt || true
          cat comparison.txt
